// This file will be generated by Supabase CLI after running the SQL schema
// For now, we'll create a placeholder structure

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          display_name: string | null
          avatar_url: string | null
          bio: string | null
          github_username: string | null
          linkedin_url: string | null
          github_data: Json
          linkedin_data: Json
          is_profile_public: boolean
          profile_rating: number | null
          profile_rating_at: string | null
          certificate_level: string | null
          community_status: string
          suspension_until: string | null
          plan: string
          stripe_customer_id: string | null
          onboarding_done: boolean
          is_evaluator: boolean
          evaluator_role: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username: string
          display_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          github_username?: string | null
          linkedin_url?: string | null
          github_data?: Json
          linkedin_data?: Json
          is_profile_public?: boolean
          profile_rating?: number | null
          profile_rating_at?: string | null
          certificate_level?: string | null
          community_status?: string
          suspension_until?: string | null
          plan?: string
          stripe_customer_id?: string | null
          onboarding_done?: boolean
          is_evaluator?: boolean
          evaluator_role?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string
          display_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          github_username?: string | null
          linkedin_url?: string | null
          github_data?: Json
          linkedin_data?: Json
          is_profile_public?: boolean
          profile_rating?: number | null
          profile_rating_at?: string | null
          certificate_level?: string | null
          community_status?: string
          suspension_until?: string | null
          plan?: string
          stripe_customer_id?: string | null
          onboarding_done?: boolean
          is_evaluator?: boolean
          evaluator_role?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      projects: {
        Row: {
          id: string
          user_id: string
          title: string
          slug: string
          description: string
          tier: string
          live_url: string
          github_url: string | null
          demo_video_url: string | null
          tech_stack: string[]
          status: string
          queue_position: number | null
          queue_entered_at: string | null
          evaluation_id: string | null
          is_public: boolean
          reaction_count: number
          comment_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          slug: string
          description: string
          tier: string
          live_url: string
          github_url?: string | null
          demo_video_url?: string | null
          tech_stack?: string[]
          status?: string
          queue_position?: number | null
          queue_entered_at?: string | null
          evaluation_id?: string | null
          is_public?: boolean
          reaction_count?: number
          comment_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          slug?: string
          description?: string
          tier?: string
          live_url?: string
          github_url?: string | null
          demo_video_url?: string | null
          tech_stack?: string[]
          status?: string
          queue_position?: number | null
          queue_entered_at?: string | null
          evaluation_id?: string | null
          is_public?: boolean
          reaction_count?: number
          comment_count?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      evaluations: {
        Row: {
          id: string
          project_id: string
          evaluator_id: string
          tier_confirmed: string
          score_total: number
          score_functionality: number
          score_ux: number
          score_complexity: number
          score_deployment: number
          score_code_quality: number
          score_documentation: number
          score_originality: number
          reviewer_note: string
          internal_notes: string | null
          community_scores: Json
          evaluated_at: string
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          evaluator_id: string
          tier_confirmed: string
          score_total: number
          score_functionality: number
          score_ux: number
          score_complexity: number
          score_deployment: number
          score_code_quality: number
          score_documentation: number
          score_originality: number
          reviewer_note: string
          internal_notes?: string | null
          community_scores?: Json
          evaluated_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          evaluator_id?: string
          tier_confirmed?: string
          score_total?: number
          score_functionality?: number
          score_ux?: number
          score_complexity?: number
          score_deployment?: number
          score_code_quality?: number
          score_documentation?: number
          score_originality?: number
          reviewer_note?: string
          internal_notes?: string | null
          community_scores?: Json
          evaluated_at?: string
          created_at?: string
        }
        Relationships: []
      }
      queue: {
        Row: {
          id: string
          project_id: string
          user_id: string
          plan: string
          position: number
          estimated_days: number | null
          assigned_to: string | null
          assigned_at: string | null
          entered_at: string
        }
        Insert: {
          id?: string
          project_id: string
          user_id: string
          plan?: string
          position: number
          estimated_days?: number | null
          assigned_to?: string | null
          assigned_at?: string | null
          entered_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          user_id?: string
          plan?: string
          position?: number
          estimated_days?: number | null
          assigned_to?: string | null
          assigned_at?: string | null
          entered_at?: string
        }
        Relationships: []
      }
      badges: {
        Row: {
          id: string
          user_id: string
          project_id: string | null
          type: string
          tier: string | null
          score: number | null
          certificate_level: string | null
          certificate_url: string | null
          pdf_url: string | null
          shareable_link: string | null
          verification_id: string
          is_valid: boolean
          issued_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          project_id?: string | null
          type: string
          tier?: string | null
          score?: number | null
          certificate_level?: string | null
          certificate_url?: string | null
          pdf_url?: string | null
          shareable_link?: string | null
          verification_id?: string
          is_valid?: boolean
          issued_at?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          project_id?: string | null
          type?: string
          tier?: string | null
          score?: number | null
          certificate_level?: string | null
          certificate_url?: string | null
          pdf_url?: string | null
          shareable_link?: string | null
          verification_id?: string
          is_valid?: boolean
          issued_at?: string
          created_at?: string
        }
        Relationships: []
      }
      project_rankings: {
        Row: {
          id: string
          period_type: string
          period_start: string
          period_end: string
          project_id: string
          evaluation_id: string
          selected_by: string | null
          selected_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          period_type: string
          period_start: string
          period_end: string
          project_id: string
          evaluation_id: string
          selected_by?: string | null
          selected_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          period_type?: string
          period_start?: string
          period_end?: string
          project_id?: string
          evaluation_id?: string
          selected_by?: string | null
          selected_at?: string | null
          created_at?: string
        }
        Relationships: []
      }
      community_posts: {
        Row: {
          id: string
          user_id: string
          project_id: string | null
          parent_id: string | null
          body: string
          is_deleted: boolean
          moderation_status: string
          reaction_count: number
          comment_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          project_id?: string | null
          parent_id?: string | null
          body: string
          is_deleted?: boolean
          moderation_status?: string
          reaction_count?: number
          comment_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          project_id?: string | null
          parent_id?: string | null
          body?: string
          is_deleted?: boolean
          moderation_status?: string
          reaction_count?: number
          comment_count?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      reactions: {
        Row: {
          id: string
          user_id: string
          community_post_id: string | null
          project_id: string | null
          reaction_type: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          community_post_id?: string | null
          project_id?: string | null
          reaction_type?: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          community_post_id?: string | null
          project_id?: string | null
          reaction_type?: string
          created_at?: string
        }
        Relationships: []
      }
      comments: {
        Row: {
          id: string
          user_id: string
          community_post_id: string | null
          project_id: string | null
          parent_comment_id: string | null
          body: string
          status: string
          is_edited: boolean
          edited_at: string | null
          reaction_count: number
          reply_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          community_post_id?: string | null
          project_id?: string | null
          parent_comment_id?: string | null
          body: string
          status?: string
          is_edited?: boolean
          edited_at?: string | null
          reaction_count?: number
          reply_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          community_post_id?: string | null
          project_id?: string | null
          parent_comment_id?: string | null
          body?: string
          status?: string
          is_edited?: boolean
          edited_at?: string | null
          reaction_count?: number
          reply_count?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      comment_reactions: {
        Row: {
          id: string
          comment_id: string
          user_id: string
          reaction_type: string
          created_at: string
        }
        Insert: {
          id?: string
          comment_id: string
          user_id: string
          reaction_type?: string
          created_at?: string
        }
        Update: {
          id?: string
          comment_id?: string
          user_id?: string
          reaction_type?: string
          created_at?: string
        }
        Relationships: []
      }
      comment_flags: {
        Row: {
          id: string
          comment_id: string
          user_id: string
          reason: string
          details: string | null
          created_at: string
        }
        Insert: {
          id?: string
          comment_id: string
          user_id: string
          reason: string
          details?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          comment_id?: string
          user_id?: string
          reason?: string
          details?: string | null
          created_at?: string
        }
        Relationships: []
      }
      moderation_log: {
        Row: {
          id: string
          user_id: string
          actioned_by: string
          comment_id: string | null
          action: string
          reason: string
          duration_days: number | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          actioned_by: string
          comment_id?: string | null
          action: string
          reason: string
          duration_days?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          actioned_by?: string
          comment_id?: string | null
          action?: string
          reason?: string
          duration_days?: number | null
          created_at?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          title: string
          body: string | null
          link: string | null
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          title: string
          body?: string | null
          link?: string | null
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          title?: string
          body?: string | null
          link?: string | null
          is_read?: boolean
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_project_comment: {
        Args: {
          p_project_id: string
          p_user_id: string
          p_body: string
          p_parent_comment_id?: string | null
        }
        Returns: string
      }
      toggle_project_reaction: {
        Args: {
          p_project_id: string
          p_user_id: string
          p_reaction?: Database['public']['Enums']['reaction_type']
        }
        Returns: boolean
      }
      flag_comment: {
        Args: {
          p_comment_id: string
          p_user_id: string
          p_reason: string
          p_details?: string | null
        }
        Returns: boolean
      }
      report_comment_for_moderation: {
        Args: {
          p_comment_id: string
          p_reporter_id: string
          p_reason: string
          p_details?: string | null
        }
        Returns: boolean
      }
    }
    Enums: {
      user_plan: 'free' | 'priority'
      community_status: 'active' | 'warned' | 'suspended' | 'banned'
      project_tier: 'tier1' | 'tier2' | 'tier3'
      project_status: 'draft' | 'submitted' | 'in_queue' | 'evaluating' | 'evaluated' | 'rejected'
      moderation_action: 'warning' | 'suspension' | 'ban' | 'reinstatement' | 'content_flag'
      badge_type: 'project_badge' | 'profile_certificate'
      certificate_level: 'provisional' | 'foundational' | 'maker' | 'builder' | 'architect'
      ranking_period: 'weekly' | 'monthly'
      reaction_type: 'like' | 'helpful' | 'insightful' | 'fire' | 'celebrate'
      comment_status: 'visible' | 'flagged' | 'hidden' | 'removed'
    }
  }
}
